### ISSUE TITLE
처방전 관련 페이지 reserve_id에 대한 문제

### ISSUE THREAD

**Issue by shinsojeong** [minsekim1/pullim#49]
[처방전 저장 부분]
1. 현재 reserve_id를 갖고 있지 않아서 meeting_number를 대신 보내주고 있는 상황입니다.
2. api가 반영된 후에 "처방전 확인 페이지"에서 처방전 정보를 저장하는 부분에서 meeting_number를  reserve_id로 변경해야 할 것 같습니다.

**Comment by gun-bro98** [comment]
확인했습니다! 풀리퀘스트로 올려볼게요
