### ISSUE TITLE
사진이 한 박자 느리게 PDF에 기입되는 이슈

### ISSUE THREAD

**Issue by gun-bro98** [minsekim1/pullim#66]
# 1. 상황
줌 프로세스 실행 중 처방전 작성하고, 처방전 확인까지는 사진에 대해서 오류가 나오지 않았습니다. 
그런데, PDF 내용을 보려고 열어보면 사진이 없고, 글만 있었습니다. 그래서 오류가 있나 싶었지만, 확인해본 결과 오류는 없었고, 
처방전을 다시 한 번 수정하고 PDF를 보았더니 아까 올라왔어야 하는 사진이 올라가 있었습니다. 

# 2. 결론
처방전에 기입한 사진이 PDF로 만들 때 한 박자 느리게 적용됩니다. 

# 3. 참고

https://github.com/minsekim1/pullim/blob/main/react/src/hook/useMakepdf.tsx#L81

**Comment by shinsojeong** [comment]
**[useMakepdf]**
처방전 다운로드/오픈 함수가 마운트 시에 생성된 후 이후 docDefinition 변경 시에 업데이트 되지 않아서 발생한 문제였습니다.
=> useCallback으로 docDefinition이 바뀔 때마다 처방전 다운로드/오픈 함수도 새로 생성되도록 하여 해결했습니다.

**Comment by gun-bro98** [comment]
넵 알겠습니다! 고생하셨습니다.
