### ISSUE TITLE
풀림 프로세스 이용시 input만 입력이 안되는 이유

### ISSUE THREAD

**Issue by gun-bro98** [minsekim1/pullim#76]
1. 상황
제가 풀림 프로세스(줌 프로세스)에서 왜 채팅이 안되는 지 여러 가지 실험을 해봤습니다.
- [x] https://www.pullim.shop/pul-lim에서 input을 만들어보기 => 실패, 다만 VScode 안에 코드를 업데이트 하다보니 input에 글을 쓸 수 있게 되었음. 그래서 리랜더링할 생각함
- [x] acceptCall이 되면 pul-lim페이지 리랜더링하기 => 실패
- [x] cookie 지우기 => 실패
- [x] localstorage 지우기 => 조금 성공, 줌 서비스가 문제라는 걸 인지하게 됨
- [x] ZoomView Component를 주석처리하고 줌만 확인해보기 => 조금 더 성공, 줌 서비스가 확실히 문제가 있다는 것을 인지하게 됨
- [x] zoom관련 패키지 Version up하기 => 실패 과거 버전(2.4.5)로 가면 해결 할 수 있지 않을까 했지만, 릴리즈 버전이 2.9.0이라 그런지 2.4.5로 되돌릴 수 없었음.
- [x] 오디오 연결하기 => 성공, 생각해보니까 오디오 연결을 안한 것 같아서 했는데 성공하였음.

2. 결론
오디오 연결을 하면 해결된다... 

3. 참조
없음.

**Comment by shinsojeong** [comment]
줌 오디오를 연결하니까 입력이 되네요 ㅠㅠ 감사합니다!👍🏻👍🏻
